### ISSUE TITLE
discord.py 1.7.3 

### ISSUE THREAD

**Issue by ayaanok** [Tom-the-Bomb/Discord-Games#19]
How to use it in discord.py 1.7.3

**Comment by Tom-the-Bomb** [comment]
It should... work if you do not try to import anything from `.button_games`

**Comment by ayaanok** [comment]
> It should... work if you do not try to import anything from `.button_games`

I'm facing this error :
'Discord' has no attribute 'ui'

**Comment by Tom-the-Bomb** [comment]
should be fixed

**Comment by ayaanok** [comment]
How to fix
