### ISSUE TITLE
I have no idea how to use this

### ISSUE THREAD

**Issue by SignalSender** [Tom-the-Bomb/Discord-Games#3]
I'm sorry if this isn't the place to put this but im new to all this stuff and I've been trying to put these on my discord bot for days now and I just cant figure out how to do it. again I apologize for putting this in issues because idk if my stupidity qualifies as an issue. I just need some help on putting these on my bot.

for more clarification the main issues im having is

1. I have no idea how to make the bot actually send these
2. I don't know exactly how this code works or what all the commands are
3. I'm stupid

thanks in advance!

**Comment by meizuflux** [comment]
easier to just dm tom on discord

**Comment by meizuflux** [comment]
or you could read the README lol

**Comment by SignalSender** [comment]
sorry like i said im new to this and don't understand the @command function very well. i didn't know the creator had a discord and the readme did not help one bit

**Comment by meizuflux** [comment]
you should not be using this if the readme is not helpful

**Comment by SignalSender** [comment]
well wouldn't you consider the readme not being descriptive enough an issue? i would. I've said twice now that im new and i do not understand most of this. I've tried copy and pasting the example and that did nothing. its just not working for me. maybe its something in my code that is messing up this code but I've been trying for days now and nothing's working.

**Comment by meizuflux** [comment]
the readme is very simple to understand if you have ample experience with d.py
