### ISSUE TITLE
BattleShip.py doesnt work

### ISSUE THREAD

**Issue by AceyDoCodes** [Tom-the-Bomb/Discord-Games#6]
the problem is that it doesnt dm me or the member
my code:
```py
import discord
from discord.ext import commands
from Discord_Games.battleship import BattleShip

class BattleShip(commands.Cog):
  def __init__(self, bot):
    self.bot = bot
  
  @commands.command()
  async def battleship(self, ctx, member: commands.MemberConverter):
    game = BattleShip(player1 = ctx.author, player2 = member)
    await game.start(ctx)
  
def setup(bot):
  bot.add_cog(BattleShip(bot))
```
all it does is sends this:
```
Game Started!
I've setup the boards in your dms!
```
anyone know how to fix this?
also i didnt get any error

**Comment by ProtDos** [comment]
Do you still need help?

**Comment by Tom-the-Bomb** [comment]
That possibly would've been a bug I did fix a few months ago, sorry but it should work now

**Comment by AceyDoCodes** [comment]
Tried again today ;-;
it tried to send the image
but...
it didnt found the image
so it gave me a `FileNotFoundError: [Errno 2] No such file or directory` error ;-;

**Comment by ProtDos** [comment]
@AceyDoCodes Do you have a folder called `assets`?
And a file called `battleship.png` in there? I'll attach the file if you don't have it.
![battleship](https://user-images.githubusercontent.com/69071809/160815902-bba9e58c-e7f5-4752-ad99-ec1718593208.png)

**Comment by Tom-the-Bomb** [comment]
Yea, I fixed that part a while ago, have you updated/reinstalled it?

**Comment by ProtDos** [comment]
I just saw this GitHub repo a short time ago. I like reinstalled it.

**Comment by AceyDoCodes** [comment]
I have updated/reinstalled it just a few days ago
but there is not an asset folder

**Comment by AceyDoCodes** [comment]
i just reinstalled it again
but there is still no asset folder

**Comment by ProtDos** [comment]
Okay. But you can create a folder and then insert the image I sent.

**Comment by Tom-the-Bomb** [comment]
that works, but Im very sure I fixed it too, how did you reinstall, have you restarted the bot etc? / try printing out __version__ ?

**Comment by ProtDos** [comment]
I've installed the newest version of it. Of course I restarted the bot. I didn't print out version. But goodthat it helped.
